### DISCUSSION TITLE
Package fast api dependencies as lambda layer not works

### DISCUSSION THREAD

**Discussion by CGarces** [awslabs/aws-lambda-web-adapter#409] [Q&A] [answered]
Hi!

I having some issues trying to run aws-lambda-web-adapter projects with a common layer with all the fast API dependencies.

Template for lambda layer:

```yaml
  FastApiLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: FastApiLayer/
      CompatibleRuntimes:
        - python3.11
    Metadata:
      BuildMethod: python3.11
      BuildArchitecture: x86_64
```
Template for lambda function:

```yaml
  FlaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: run.sh
      Runtime: python3.11
      MemorySize: 128
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/bootstrap
          PORT: 8000
      Layers:
        - !Sub arn:aws:lambda:${AWS::Region}:753240598075:layer:LambdaAdapterLayerX86:20
        - Fn::ImportValue: "backend-layers-FastApiLayer"
```

requirements.txt for lambda layer
```
fastapi~=0.109.2
uvicorn[standard]==0.27.1
pydantic==2.6.1
```
And finally the run.sh

```bash
#!/bin/bash
exec python -m uvicorn --port=$PORT app:app
```

I get the following error `/var/lang/bin/python: No module named uvicorn`

Something is different in the way that SAM deploy the package with and without the lambda layer.

I have unziped the layer, and the original function (with the dependencies, not the layer) and I can't see the diff except for the folder structure.
The layer package all the dependencies at "/python/" folder, that according to the documentation, is de correct way.

original funcion:

- root
   - my code
   - uvicorn
   - uvicorn-0.27.1.dist-info

Lambda layer:

- root
   - python/
     - uvicorn
     - uvicorn-0.27.1.dist-info

Y need to change anything in the run.sh file to work with uvicorn inside a lambda layer?
