### ISSUE TITLE
cargo-lambda usage?

### ISSUE THREAD

**Issue by jplock** [awslabs/aws-lambda-web-adapter#334]
Fellow Amazonian here 👋 

I've been working on porting a Python-based Lambda Extension to Rust so any runtime can use it. I've been using this repo as a guide during my efforts and recently came across [cargo-lambda](https://www.cargo-lambda.info) and wondered why this repository wasn't using it?

My eventual intention with my extension would be to publish it as a Lambda layer for anyone to use in their applications, which is a similar use case to the lambda web adapter.

I wanted to continue using AWS SAM to build my Rust-based Lambda layer.  This is working for me:

#### template.yml
```yaml
ExtensionsLayerX86:
    Type: "AWS::Serverless::LayerVersion"
    Metadata:
      BuildMethod: makefile
      BuildArchitecture: x86_64
    Properties:
      LicenseInfo: Apache-2.0
      CompatibleArchitectures:
        - x86_64
      ContentUri: .
      Description: !Sub "${AWS::StackName} - DynamoDB Extension Layer (Rust/x86_64)"
      RetentionPolicy: Delete
```

#### Makefile
```makefile
build-ExtensionsLayerX86:
	cargo lambda build --release --extension --x86-64 --lambda-dir $(ARTIFACTS_DIR)
```

Then I can use the normal `sam build` (without using `--use-container`) and `sam deploy`. This also avoids needing Docker and setting up the rustbuilder and all that.
