### ISSUE TITLE
No `body` attribute in s3 events

### ISSUE THREAD

**Issue by michalbujalski** [awslabs/aws-lambda-web-adapter#455]
I want to be able to handle new file uploads to s3 bucket

My SAM setup
```
 ServerlessFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      MemorySize: 1024
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref EcommerceChatApi
            Path: /
            Method: ANY
        Conversations:
          Type: Api
          Properties:
            RestApiId: !Ref EcommerceChatApi
            Path: /{proxy+}
            Method: ANY
        UploadFileEvent:
          Type: S3
          Properties:
            Bucket: !Ref MyS3Bucket
            Events: s3:ObjectCreated:*
    Metadata:
      DockerTag: v1
      DockerContext: ./app
      Dockerfile: Dockerfile


MyS3Bucket:
    Type: AWS::S3::Bucket

LambdaInvokePermission:
  Type: 'AWS::Lambda::Permission'
  Properties:
    FunctionName: !GetAtt ServerlessFunction.Arn
    Action: 'lambda:InvokeFunction'
    Principal: 's3.amazonaws.com'
    SourceArn: !GetAtt MyS3Bucket.Arn
```

My backend code is exactly the same as in the SQS example:

```
app.post('/events', (req, res) => {
  console.log('Event:')
  console.log('-----')
  console.log(req.body)
  console.log('-----')
  res.json('success')
})
```

Neither `body` nor `Records` are present in the payload. Am I missing something or is this a bug?
